# version: "3"
# services:
#   db:
#     image: "postgres"
#     container_name: "my_postgres"
#     ports:
#       - "5432:5432"

# version: '3'
# services:
#   flyway:
#     image: boxfuse/flyway
#     command: -url=jdbc:postgresql://db/postgres -schemas=schemaName -user=user -password=pwd migrate
#     volumes:
#       - ./flyway:/flyway/sql
#     depends_on:
#       - db
#   db:
#     image: "postgres"
#     ports:
#       - 5432:5432
#     environment:
#     - POSTGRES_PASSWORD=pwd
#     healthcheck:
#       test: "pg_isready -q -U postgres"

# jdbc:postgresql://host:port/database

# version: '3'
# services:
#   flyway:
#     image: boxfuse/flyway
#     command: -url=jdbc:postgresql://db/ -user=postgres -password=P@ssw0rd -connectRetries=300 migrate
#     volumes:
#     - .:/flyway/sql
#     depends_on:
#     - db
#   db:
#     image: postgres
#     environment:
#     - POSTGRES_USER=postgres
#     - POSTGRES_PASSWORD=P@ssw0rd
#   flask:
#     image: service-odds-machine:latest
#     depends_on:
#     - db

