apiVersion: v1
kind: Service        # Type of Kubernetes resource
metadata:
  name: flask-service # Name of the Kubernetes resource
  labels:            # Labels that will be applied to this resource
    app: service-odds-machine
spec:
  ports:
  - name: flask-http
    port: 5000       # Map incoming connections on port 6379 to the target port 6379 of the Pod
    targetPort: 5000
    protocol: TCP
  selector:          # Map any Pod with the specified labels to this service
    app: service-odds-machine-container
  type: NodePort