pipeline {
    environment {
        DOCKER = credentials('docker-hub')
    }
    agent any
        stages {
            stage('Build') {
                steps {
                    sh 'docker build -f Dockerfile \
                    -t service-odds-machine:latest .'
                }
                post {
                    failure {
                        echo 'This build has failed. See logs for details.'
                    }
                }
            }
            stage('Deploy') {
                when {
                    branch 'master'
                }
                steps {
                    retry(3) {
                        timeout(time:10, unit: 'MINUTES') {
                            sh 'docker login --username $DOCKER_USR --password $DOCKER_PSW'
                            sh 'docker tag service-odds-machine:latest ace149/service-odds-machine:latest'
                            sh 'docker push ace149/service-odds-machine:latest'
                            sh 'docker save ace149/service-odds-machine:latest | gzip > service-odds-machine-prod-golden.tar.gz'
                        }
                    }
                    echo 'This is the Deploy Stage'
                }
            }
        }
    }